### ISSUE TITLE
Run Example

### ISSUE THREAD

**Issue by Wikiko** [juicycleff/flutter-unity-arkit-demo#5]
Hello, I tried to run your example of AR. But I can't

Can you help me?

The log of flutter run is:

Launching lib/main.dart on Redmi Note 8 in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':flutter_unity_widget:generateDebugRFile'.
> Could not resolve all task dependencies for configuration ':flutter_unity_widget:debugRuntimeClasspath'.
   > Could not find :ARPresto:.
     Required by:
         project :flutter_unity_widget > project :UnityExport
   > Could not find :UnityARCore:.
     Required by:
         project :flutter_unity_widget > project :UnityExport
   > Could not find :UnityAds:.
     Required by:
         project :flutter_unity_widget > project :UnityExport
   > Could not find :UnityAdsAndroidPlugin:.
     Required by:
         project :flutter_unity_widget > project :UnityExport
   > Could not find :arcore_client:.
     Required by:
         project :flutter_unity_widget > project :UnityExport
   > Could not find :unityandroidpermissions:.
     Required by:
         project :flutter_unity_widget > project :UnityExport

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by supermnemonic** [comment]
i have same problem. how did you solve it?

**Comment by Jatin-Pawar** [comment]
Simply follow the following steps:
1) Open the "android" folder as a project in Android Studio.
2) Now, try to import .aar files by File > New > New Module > Import .JAR/AAR Package > Select android/UnityExport/libs/arcore-client.aar (This should import the files without any error.)
3) After step 2, you can check your UnityExport/settings.gradle file to find out that `include` ':arcore_client'` has been added at the top. (If not kindly add it.)
4) Repeat the above 2 steps for all the .arr/.jar files in the UnityExport/libs folder.
