### ISSUE TITLE
Exception: Build failed Build.DoBuildIOS () (at Assets/Editor/Build.cs:94)

### ISSUE THREAD

**Issue by anyataa** [juicycleff/flutter-unity-arkit-demo#7]
# Flutter Export IOS build Failed on Unity

Please help, is this something wrong because i miss some steps or is it bug?

i am exporting using Flutter Export IOS on Unity version 2019.4.4f1 LTS and here's what i got

## Error 1 - Used from several location
Plugin 'UnityARKit.a' is used from several locations:
 Packages/com.unity.xr.arkit/Runtime/iOS/Xcode1100/UnityARKit.a would be copied to <PluginPath>/UnityARKit.a
 Packages/com.unity.xr.arkit/Runtime/iOS/Xcode1000/UnityARKit.a would be copied to <PluginPath>/UnityARKit.a
Plugin 'libUnityARKitFaceTracking.a' is used from several locations:
 Packages/com.unity.xr.arkit-face-tracking/Runtime/iOS/Xcode1100/libUnityARKitFaceTracking.a would be copied to <PluginPath>/ARM64/libUnityARKitFaceTracking.a
 Packages/com.unity.xr.arkit-face-tracking/Runtime/iOS/Xcode1000/libUnityARKitFaceTracking.a would be copied to <PluginPath>/ARM64/libUnityARKitFaceTracking.a
Please fix plugin settings and try again.

## Error 2 - Colliding with each other
UnityEditor.Modules.DefaultPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
UnityEditor.BuildPipeline:BuildPlayer(String[], String, BuildTarget, BuildOptions)
Build:DoBuildIOS() (at Assets/Editor/Build.cs:86)

Plugins colliding with each other.

## Error 3 - Warning
Exception: Build failed
Build.DoBuildIOS () (at Assets/Editor/Build.cs:94)

**Comment by anyataa** [comment]
I solved the issue by deleting the Xcode 1000 version directory for both ArKit Face and ArKit Plug in from my Library directory in Unity

- the dir is place here 
/Users/anyata/AndroidStudioProjects/flutter-unity-arkit-demo/unity/ARDemoApp/Library/PackageCache/com.unity.xr.arkit-face-tracking@3.0.0-preview.3/Runtime

you could do the same for the ArKit PlugIn make sure to delete the unused version of XCode for me it was Xcode version 10 since i use version 11. After deleting the dir Unity didn't confused anymore and succeed the build

Hope i save someone else to bug in these issue

**Comment by Darik04** [comment]
> I solved the issue by deleting the Xcode 1000 version directory for both ArKit Face and ArKit Plug in from my Library directory in Unity
> 
> * the dir is place here
>   /Users/anyata/AndroidStudioProjects/flutter-unity-arkit-demo/unity/ARDemoApp/Library/PackageCache/com.unity.xr.arkit-face-tracking@3.0.0-preview.3/Runtime
> 
> you could do the same for the ArKit PlugIn make sure to delete the unused version of XCode for me it was Xcode version 10 since i use version 11. After deleting the dir Unity didn't confused anymore and succeed the build
> 
> Hope i save someone else to bug in these issue

Thank you so much, you solved my issue!
